const LINKS = [
	['Rezept Walnussbrot', 'https://kochfokus.de/artikel/rezept-walnussbrot/'],
	['Country Cookies à la Gabi', 'https://kochfokus.de/artikel/country-cookies/'],
	['Einfacher Apfelkuchen', 'https://kochfokus.de/artikel/einfacher-apfelkuchen/'],
	['Spaghettipfanne mit Hähnchen an mediterranem Gemüse', 'https://kochfokus.de/artikel/spaghettipfanne-mit-haehnchen-an-mediterranem-gemuese/'],
	['Cremige Kartoffelsuppe mit Safran veredelt', 'https://kochfokus.de/artikel/cremige-kartoffelsuppe-mit-safran-veredelt/'],
	['Haferflockenpancakes mit Kokosmehl und Cranberries', 'https://kochfokus.de/artikel/kokospancakes-mit-cranberries-so-gut/'],
	['Cranberry Chutney mit Clementinen - so vortrefflich!', 'https://kochfokus.de/artikel/cranberry-chutney-mit-clementinen-so-vortrefflich/'],
	['Schichtdessert im Glas | Resteverwertung de Luxe', 'https://kochfokus.de/artikel/schichtdessert-im-glas-resteverwertung-de-luxe/'],
	['Eisbärtatzen', 'https://kochfokus.de/artikel/eisbaertatzen/'],
	['Hallo! Ich bin Gabi', 'https://kochfokus.de/about-me/'],
	['Datenschutzerklärung Instagram', 'https://img.kfcdn.de/other/docs/instagram-privacy.html'],
	['Webseite', 'https://kochfokus.de'],
	['YouTube', 'https://www.youtube.com/user/kochfokusTV/'],
	['Facebook', 'https://www.facebook.com/kochfokusDE/'],
	['Twitter', 'https://twitter.com/kochfokusDE/'],
	['Instagram', 'https://instagram.com/kochfokus.de/'],
	['Pinterest', 'https://www.pinterest.com/kochfokus/'],
	['Flipboard', 'https://flipboard.com/@kochfokusde/'],
];
