const LINKS = [
	['Ein Teig - 3 Arten von Plätzchen', 'https://kochfokus.de/artikel/ein-teig-3-verschiedene-arten-von-plaetzchen-der-weihnachtsbaeckerei/'],
	['Bethmännchen', 'https://kochfokus.de/artikel/bethmaennchen/'],
	['No Knead Weihnachtsbrot - ideal für Hefeteiganfänger', 'https://kochfokus.de/artikel/no-knead-weihnachtsbrot-ideal-fuer-hefeteiganfaenger/'],
	['Himmlische Johannisbeer Lebkuchenaugen', 'https://kochfokus.de/artikel/himmlische-johannisbeer-lebkuchenaugen/'],
	['Country Cookies à la Gabi', 'https://kochfokus.de/artikel/country-cookies/'],
	['Weihnachtliche Müslimuffins', 'https://kochfokus.de/artikel/weihnachtliche-mueslimuffins/'],
	['Cremige Kartoffelsuppe mit Safran veredelt', 'https://kochfokus.de/artikel/cremige-kartoffelsuppe-mit-safran-veredelt/'],
	['Hallo! Ich bin Gabi', 'https://kochfokus.de/about-me/'],
	['Datenschutzerklärung Instagram', 'https://img.kfcdn.de/other/docs/instagram-privacy.html'],
	['Webseite', 'https://kochfokus.de'],
	['YouTube', 'https://www.youtube.com/user/kochfokusTV/'],
	['Facebook', 'https://www.facebook.com/kochfokusDE/'],
	['Twitter', 'https://twitter.com/kochfokusDE/'],
	['Instagram', 'https://instagram.com/kochfokus.de/'],
	['Pinterest', 'https://www.pinterest.com/kochfokus/'],
	['Flipboard', 'https://flipboard.com/@kochfokusde/'],
];
